name: Android Release Build

on:
  release:
    types: [ published ]

jobs:
  validation:
    name: Gradle wrapper Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

  build:
    needs: validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permissions
        run: chmod +x gradlew

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Provide Firebase config to app module
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > ./app/google-services.json

      - name: Provide Firebase config to online module
        run: echo $FIREBASE_CONFIG > ./online/google-services.json

      - name: Build with gradle
        run: ./gradlew buildRelease

  unit-tests:
    needs: validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permissions
        run: chmod +x gradlew
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Provide Firebase config to app module
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > ./app/google-services.json

      - name: Provide Firebase config to online module
        run: echo $FIREBASE_CONFIG > ./online/google-services.json

      - name: Run tests
        run: ./gradlew testRelease

      - name: Output test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit test results
          path: "**/build/reports/tests/testReleaseUnitTest/"

  instrumented-test:
    needs: validation
    runs-on: macos-latest
    timeout-minutes: 60
    strategy:
      matrix:
        api_level: [ 21, 24, 27, 30 ]
        target: [ default, google_apis ]
        exclude:
          # Excluding as 30-default is not supported by emulator yet
          - api_level: 30
            target: default

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permissions
        run: chmod +x gradlew

      - name: Provide Firebase config to app module
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > ./app/google-services.json

      - name: Provide Firebase config to online module
        run: echo $FIREBASE_CONFIG > ./online/google-services.json

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: AVD cache
        id: avd-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api_level }}-${{ matrix.target }}

        # If a cache doesn't exist, create one.
      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api_level }}
          target: ${{ matrix.target }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api_level }}
          target: ${{ matrix.target }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew core:connectedAndroidTest app:connectedAndroidTest -DtestBuildType=release

      - name: Output test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Instrumented test results (${{ matrix.api_level }}-${{ matrix.target }})
          path: "**/build/reports/androidTests/connected"


  release:
    needs: [ build, unit-tests, instrumented-test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permissions
        run: chmod +x gradlew

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Provide Firebase config to app module
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > ./app/google-services.json

      - name: Provide Firebase config to online module
        run: echo $FIREBASE_CONFIG > ./online/google-services.json

      - name: Build App bundle with Gradle
        run: ./gradlew app:bundleRelease

      - name: Build Universal APK with Gradle
        run: ./gradlew packageReleaseUniversalApk

      - name: Sign Android release - App bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_app_bundle
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Sign Android release - APK
        uses: r0adkll/sign-android-release@v1
        id: sign_apk
        with:
          releaseDirectory: app/build/outputs/universal_apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Get release details
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release App bundle to Github Releases
        id: upload-release-bundle
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ steps.sign_app_bundle.outputs.signedReleaseFile }}
          asset_name: Healers-Diary-${{ steps.get_release.outputs.tag_name }}.aab
          asset_content_type: application/octet-stream

      - uses: actions/upload-artifact@v2
        name: Upload Release App bundle to this action
        with:
          name: Healers-Diary-${{ steps.get_release.outputs.tag_name }}.aab
          path: ${{steps.sign_app_bundle.outputs.signedReleaseFile}}

      - name: Upload Release APK to Github Releases
        id: upload-release-apk
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ steps.sign_apk.outputs.signedReleaseFile }}
          asset_name: Healers-Diary-${{ steps.get_release.outputs.tag_name }}.apk
          asset_content_type: application/vnd.android.package-archive

      - uses: actions/upload-artifact@v2
        name: Upload Release APK to this action
        with:
          name: Healers-Diary-${{ steps.get_release.outputs.tag_name }}.apk
          path: ${{steps.sign_apk.outputs.signedReleaseFile}}

  # Create a PR to merge changes in desired branch
  merge-release:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Get release details
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set merge branch as production if not a prerelease
        if: steps.get_release.outputs.prerelease != 'true'
        run: echo "branch=releases/production" >> $GITHUB_ENV

      - name: Set merge branch as beta if it is a prerelease
        if: steps.get_release.outputs.prerelease == 'true' && contains( steps.get_release.outputs.tag_name, 'beta')
        run: echo "branch=releases/beta" >> $GITHUB_ENV

      - name: Create Release pull request
        uses: repo-sync/pull-request@v2
        with:
          pr_title: ${{ steps.get_release.outputs.tag_name }} Release
          pr_body: ${{ steps.get_release.outputs.body }}
          source_branch: master
          destination_branch: ${{ env.branch }}
          pr_label: release
          pr_assignee: yashovardhan99
          pr_reviewer: yashovardhan99
          github_token: ${{ secrets.GITHUB_TOKEN }}