name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permissions
        run: chmod +x gradlew

      - name: Provide Firebase config to app module
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > ./app/google-services.json

      - name: Provide Firebase config to online module
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > ./online/google-services.json

      - name: Build with Gradle
        run: ./gradlew buildDebug

  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api_level: [21, 24, 27, 30]
        target: [default, google_apis]

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permissions
        run: chmod +x gradlew

      - name: Provide Firebase config to app module
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > ./app/google-services.json

      - name: Provide Firebase config to online module
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > ./online/google-services.json

      - name: Unit tests
        run: ./gradlew testDebug

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api_level }}
          target: ${{ matrix.target }}
          script: ./gradlew connectedAndroidTest
