name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permissions
        run: chmod +x gradlew

  build:
    runs-on: macos-latest
    needs: setup
    steps:
      - name: Build with Gradle
        run: ./gradlew buildDebug

  test:
    runs-on: macos-latest
    needs: setup
    stratergy:
      matrix:
        api_level: [21, 24, 27, 30]
        target: [default, google_apis]
    steps:
      - name: Unit tests
        run: ./gradlew testDebug

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          script: ./gradlew connectedAndroidTest
